name: dart_code_metrics
version: 5.7.6
description: Software analytics tool that helps developers analyse and improve software quality.
homepage: https://dcm.dev/
repository: https://github.com/dart-code-checker/dart-code-metrics
issue_tracker: https://github.com/dart-code-checker/dart-code-metrics/issues
documentation: https://dcm.dev/docs/getting-started/

environment:
  sdk: ">=3.1.5 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: 6.2.0
  analyzer_plugin: ^0.11.3
  ansicolor: ^2.0.2
  args: ^2.4.2
  collection: ^1.17.2
  crypto: ^3.0.3
  dart_code_metrics_presets: ^2.7.0
  file: ^7.0.0
  glob: ^2.1.2
  html: ^0.15.4
  http: ^0.13.6
  meta: ^1.9.1
  path: ^1.8.3
  platform: ^3.1.3 # overridden for lowest versions compatibility
  source_span: ^1.10.0
  uuid: ^4.2.1
  xml: ^6.4.2
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.1
  intl: ^0.19.0
  lints: ^3.0.0
  mocktail: ^1.0.1
  test: ^1.24.9

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
